# Chapter 3: Introduction to Keras and Tensorflow

## 3.5.1 Constant tensors and variables

In [ ]:
import tensorflow as tf

In [ ]:
x = tf.ones(shape=(2,1), dtype='int32')
x

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [1]], dtype=int32)>

In [ ]:
y = tf.zeros(shape=(2,1), dtype='int32')
y

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[0],
       [0]], dtype=int32)>

In [ ]:
#normal distribution
x1 = tf.random.normal(shape=(3,1), mean=0, stddev=1)
x1

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[ 0.41368678],
       [-1.1947001 ],
       [-0.41598797]], dtype=float32)>

In [ ]:
#uniform distribution
x1 = tf.random.uniform(shape=(3,1), minval=0., maxval=1.)
x1

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.37322795],
       [0.5900518 ],
       [0.20933068]], dtype=float32)>

In [ ]:
#creating a tensorflow variable 
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.9001828 ],
       [-0.63813406],
       [ 0.02958672]], dtype=float32)>

In [ ]:
#Assigning a value to a TensorFlow variable
#complete changes the original variable
v.assign(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [ ]:
#assing a value to a subset of the variable
v[0, 0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [ ]:
# add values like =+ or substract values like -=
v.assign_add(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

## 3.5.2 Tensor operations: Doing math in TensorFlow

In [ ]:
a = tf.Variable(tf.ones((2, 2)))
a.assign_add([[1,2],[3,4]])
b = tf.square(a)
a, b

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>)

In [ ]:
c = tf.sqrt(a)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4142135, 1.7320508],
       [2.       , 2.236068 ]], dtype=float32)>

In [ ]:
d = b + c
d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 5.4142137, 10.732051 ],
       [18.       , 27.236069 ]], dtype=float32)>

In [ ]:
#Matrix multiplication A x B
e = tf.matmul(a, b) 
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 56.,  93.],
       [ 96., 161.]], dtype=float32)>

In [ ]:
#Multiplication of elements in the same positions
e *= d
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[  1641.5676,  10711.453 ],
       [ 31104.    , 119430.34  ]], dtype=float32)>

In [ ]:
tf.square(tf.Variable(initial_value=3.))

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

## 3.5.3 A second look at the GradientTape API

In [ ]:
#Get the gradient of any differentiable expression
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
   result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
result, gradient

(<tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.0>)

In [ ]:
#Get the gradient of constant tensor inputs
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
   tape.watch(input_const)
   result = tf.square(input_const)
gradient = tape.gradient(result, input_const)
result, gradient

(<tf.Tensor: shape=(), dtype=float32, numpy=9.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [ ]:
#Using nested gradient tapes to compute second-order gradients
time = tf.Variable(5.)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position =  4.9 * time ** 2
    speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)
time, position, speed, acceleration

(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=122.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=49.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.8>)

In [ ]:
4.9*2

9.8